version: '3'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
  frontend:
    build:
      context: frontend
    links:
      - backend
    ports:
      - 80:80
  backend:
    build:
      context: backend
    links:
      - database
    environment:
      - PORT=80
      - AUTH_SECRET=despacito2vie
      - MONGO_URI=mongodb://database/launcher
